INSERT INTO CUSTOMER(
  CUST_NUM,
  CUST_LNAME,
  CUST_FNAME,
  CUST_BALANCE
) VALUES(1000, "Smith", "Jeanne", 1050.11);

INSERT INTO CUSTOMER(
  CUST_NUM,
  CUST_LNAME,
  CUST_FNAME,
  CUST_BALANCE
) VALUES(1001, "Ortega", "Juan", 840.92);
