INSERT INTO CUST_MYSQL(
  CUST_LNAME,
  CUST_FNAME,
  CUST_BALANCE
) VALUES("Smith", "Jeanne", 1050.11);

INSERT INTO CUST_MYSQL(
  CUST_LNAME,
  CUST_FNAME,
  CUST_BALANCE
) VALUES("Ortega", "Juan", 840.92);
