select LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME
from LGEMPLOYEE join LGDEPARTMENT
where EMP_TITLE like "%ASSOCIATE" and LGEMPLOYEE.DEPT_NUM = LGDEPARTMENT.DEPT_NUM
order by DEPT_NAME, EMP_TITLE, EMP_NUM
